### ISSUE TITLE
Testi da aggiornare monitutor

### ISSUE THREAD

**Issue by luigireggi** [level73/Monithon#100]
In verde nel solito doc (riga 5 e 6): https://docs.google.com/spreadsheets/d/1RSoqw-x_AQzCioSBygMU5opSotFRbf4xPPjD5geF0KU/edit#gid=0
In riga 6 c'è una nuova tipologia di progetto con nuovi testi: Tema = Ambiente; Sottotema = Piste ciclabili e percorsi pedonali

**Comment by IronRunes** [comment]
done.
