### ISSUE TITLE
Sostituire mail

### ISSUE THREAD

**Issue by luigireggi** [level73/Monithon#101]
redazione.monithon@gmail.com > redazione@monithon.eu

**Comment by luigireggi** [comment]
... anche un bell'alias sul server

**Comment by IronRunes** [comment]
non posso fare sta cosa io su server, @luigireggi 
tu puoi mettere un forward da redazione.monithon@gmail verso redazione@monithon.eu e risolvere una quota parte
per cambiare il sender ho bisogno della pwd dell'account in questione

**Comment by luigireggi** [comment]
la password è la stessa, te la rimando cmq
