### ISSUE TITLE
testo su licenza in it.monithon.eu/main

### ISSUE THREAD

**Issue by luigireggi** [level73/Monithon#102]
La metodologia, gli strumenti e i dati prodotti da Monithon sono pubblicati con licenza aperta Creative Commons BY 4.0. E’ possibile riutilizzarli liberamente citando Monithon come fonte e indicando eventuali modifiche effettuate.

< Immagine CC-BY nel footer del wordpress >

**Comment by luigireggi** [comment]
Sorry vorrei cambiare la licenza

La metodologia, gli strumenti e i dati prodotti da Monithon sono pubblicati con licenza aperta Creative Commons BY NC 4.0. E’ possibile riutilizzarli liberamente – tranne che per scopi commerciali – citando Monithon come fonte e indicando eventuali modifiche effettuate.

**Comment by luigireggi** [comment]
UPDATE:

La metodologia, gli strumenti e i dati prodotti da Monithon sono pubblicati con licenza aperta Creative Commons BY SA 4.0. E’ possibile riutilizzarli e distribuirli liberamente citando Monithon come fonte, inserendo il link al contenuto e indicando eventuali modifiche effettuate. Si applica la stessa licenza in caso di riutilizzo: se si remixano e trasformano i metodi, i dati, gli strumenti o i materiali, vanno distribuiti con la stessa licenza CC BY SA.

**Comment by IronRunes** [comment]
fatto.
