### ISSUE TITLE
DEVELOPMENT: pagina per user con logo, bio, etc.

### ISSUE THREAD

**Issue by luigireggi** [level73/Monithon#106]

**Comment by IronRunes** [comment]
@luigireggi Logo | Bio | Elenco Report approvati | Social, links | Link ad Asoc?
ci viene in mente altro da aggiungere a questa pagina?

**Comment by luigireggi** [comment]
Ora non mi viene in mente niente altro.
In futuro, se qualche utente fa dei post sul wordpress si potrebbero embeddare o linkare

**Comment by IronRunes** [comment]
completato
