### ISSUE TITLE
tipo utente: ASOC1920 > ASOC2021

### ISSUE THREAD

**Issue by luigireggi** [level73/Monithon#107]

**Comment by IronRunes** [comment]
cosa intendi @luigireggi ? mi è parecchio oscura questa issue

**Comment by luigireggi** [comment]
:-) c'è un tipo utente che si chiama ASOC1920. O lo cambiamo in "ASOC" oppure in "ASOC2021"... 2122.. etc

**Comment by IronRunes** [comment]
ah ok - sono diventati tutti quanti ASOC piatto
