### ISSUE TITLE
Ricerca indirizzo in mappa funziona solo col CAP

### ISSUE THREAD

**Issue by luigireggi** [level73/Monithon#11]

**Comment by sirmmo** [comment]
io "baravo", nella vecchia versione, usando il sistema di geocoding di mappina che usava una sequenza di ricerche: nominatim, poi opencages, poi credo openaddresses, poi mapbox poi google (ma su google non arrivava mai). se in uno dei passaggi trovava una soluzione la ritornava

**Comment by sirmmo** [comment]
una soluzione simile è quella fornita da https://hub.docker.com/repository/docker/modalnodes/geocoder che fa esattamente questo in modo "diretto". per la documentazione la cerco e ve la posso mandare, se vi serve.

**Comment by IronRunes** [comment]
grazie @sirmmo , me la studio sul codice della tua versione, hai modo di indicarmi dove la trovo? :)

**Comment by luigireggi** [comment]
manda manda tutto ing ;)

**Comment by sirmmo** [comment]
scusate, mi ero perso il msg, meno male che @luigireggi mi scrive su telegram... xD 
cerco e vi mando

**Comment by luigireggi** [comment]
a stalking non mi batte nessuno :D

**Comment by luigireggi** [comment]
Forse in attesa dell'Ing potremmo modificare la label della domanda dicendo "inserire anche il CAP"

**Comment by IronRunes** [comment]
abbiamo constato come su OpenStreetMap alle volte il CAP potrebbe non bastare. Immagino sia uno dei motivi per cui @sirmmo usava più motori di geocoding per trovare una risposta soddisfacente. ;) 
Procedo a cercarmi le indicazioni sul codice del repo e vi aggiorno!

**Comment by IronRunes** [comment]
potenziale candidato per risolvere il problema: 
https://github.com/smeijer/leaflet-geosearch

**Comment by IronRunes** [comment]
Implementato il CAP, i risultati migliorano ma non sono ancora precisissimi.
