### ISSUE TITLE
pagina profilo monithon redazione

### ISSUE THREAD

**Issue by luigireggi** [level73/Monithon#111]
https://it.monithon.eu/profile/view/349
ci sono report di vari utenti

cliccando sull'utente di questo report si finisce nella pagina sopra: https://it.monithon.eu/report/view/877

**Comment by luigireggi** [comment]
stessa cosa per questo report dello stesso team freedam
https://it.monithon.eu/report/view/716

**Comment by IronRunes** [comment]
Sono i report migrati in batch cui mancavano dei dati per la creazione degli utenti. Bisogna fare un po di matching a mano

**Comment by luigireggi** [comment]
Puoi fare un file?

**Comment by IronRunes** [comment]
Questo è stato fixato con il lavorone sui profili :D
