### ISSUE TITLE
Link a guida FSC

### ISSUE THREAD

**Issue by luigireggi** [level73/Monithon#2]
Consulta a href="https://opencoesione.gov.it/media/uploads/relazione_fsc_regionale_2007_2013.pdf">questa relazione sull’utilizzo del Fondo Sviluppo e Coesione nel 2007-13.

Es. https://opencoesione.gov.it/it/progetti/1mise788/

**Comment by IronRunes** [comment]
@luigireggi è sempre lo stesso link o devo prenderlo dalla tabella dei PO?

**Comment by luigireggi** [comment]
no no il link è giusto, è solo refuso su HTML
