### ISSUE TITLE
Guida ai beni confiscati non appare

### ISSUE THREAD

**Issue by luigireggi** [level73/Monithon#21]

**Comment by IronRunes** [comment]
Al momento pubblica suggerimenti per tema e BCM, ma se decidiamo di dare priorità assoluta al tema trasversale BCM allora: 

- [ ] eliminare doppio suggerimento in STEP 2 (Block 5)
- [ ] pubblicare solo esempi per beni confiscati STEP 2 (Block 6) 
- [ ] eliminare pubblicazione tema (tentative)

**Comment by luigireggi** [comment]
Ho visto i progetti e teniamo entrambi i suggerimenti (tema + tema trasversale BCM).
Per me si può chiudere la issue
