### ISSUE TITLE
Maquillage Gen 2020

### ISSUE THREAD

**Issue by IronRunes** [level73/Monithon#23]
- [x]  Testo iniziale: "Inserisci la URL per fare apparire MonitTutor...." o simili
- [x]  placeholder = "URL del progetto scelto”

STEP1 

- [x] Inserire “MoniTutor" Step 1
- [ ] Reminder: "se il progetto è già stato monitorato..." ha priorità alta
- [x] Inserire testo introduttivo step 1 (vedi slides)
- [x] Obiettivo specifico è ND o non appare (Esempio https://opencoesione.gov.it/it/progetti/4mtra111103/
- [x] Cambiare testo per suggerimenti tematici (vedi slides)
- [x] CAP in mappa

STEP 2

- [x] Aggiungere “MoniTutor”
- [x] “ancora in corso” o “concluso” in BOLD.
- [x] Colori: rosso o giallo o …? (ne userei 2 al max)
- [x] Aggiungere in fondo a testo introduttivo: “Quando hai finito, compila le domande più sotto”.
- [x] Più evidenti i titoli di sessione (verde)
- [x] Tutti i soggetti sono “pari”, hanno stesso format grafico e compaiono solo se esistono: evidenziare il tipo di soggetto (es. “referenti politici”, etc.). Per i soggetti di OC abbiamo detto ok se "ND".
- [x] L'ordine dei soggetti OC: programmatore, beneficiario, attuatore, realizzatore
- [x] Programmatori: "Ambiente ed energia” invece che nome del soggetto
- [x] “intervista i giornalisti....” è duplicato
- [x] Togliere autore del suggerimento (nei vari posti in cui è). farei testo unico con i credits. Alan, io metterei nei credits anche il logo di level73 che nel footer è molto evidente. Ne parliamo!
- [x] La tabella è un po’ lunga, forse si può diminuire il font.
- [x] Tra “Scegli le domande” e la tabella togliere la riga di divisione
- [ ] A volte dopo il tema c’è trattino per un sottotema che non c'è... (nice to have!)

**Comment by IronRunes** [comment]
- [x] Ultimo blocco S1, primo paragrafetto ("secondo opencoesione" etc etc) diventa titolo del blocco

**Comment by luigireggi** [comment]
- [x] penultimo blocco.  **Titolo** = "Cerca dati e informazioni di contesto".  **Corpo** _(cambia solo il primo paragrafo)_ = "E’ importante inquadrare il singolo progetto scelto nell’ambito di un contesto più ampio.
Molti spunti per valutare il singolo progetto si possono ottenere dopo essersi fatti un’idea su quali sono i problemi e le opportunità di una città, di una regione o di un settore, e come le politiche pubbliche cercano di rispondere."

- [x] ultimo blocco. Titolo = "Segui i nostri link a siti web e documenti sul tema a cui appartiene il progetto".

Vedi anche https://docs.google.com/presentation/d/1zQ0s_2xvFQaLduqQsyr8vX82ku_BGmCBoqY4jeYk1AM/edit#slide=id.p

**Comment by luigireggi** [comment]
Autori ancora presenti in S2:

- "Ulteriori tipologie di soggetti da contattare dipendono dal tema più generale in cui, secondo OpenCoesione...."
- "Ulteriori domande dipendono dal tema prevalente in cui, secondo OpenCoesione, è classificato il progetto da monitorare..."

**Comment by IronRunes** [comment]
Finito. 
Sposto la questione dei progetti già monitorati in altra issue
