### ISSUE TITLE
Report 136: l'ultimo video va sotto il footer

### ISSUE THREAD

**Issue by luigireggi** [level73/Monithon#32]
aggiungere spazietto tra le risorse (colonna sx) e il footer

**Comment by luigireggi** [comment]
ora il video è tagliato

**Comment by IronRunes** [comment]
Provato con un hard refresh?

**Comment by luigireggi** [comment]
Sì ma ora vedo che...... hanno embeddato il sito del TGR rai..... vabbé lasciamo perdere :)
