### ISSUE TITLE
Report 169 pagina view da errori

### ISSUE THREAD

**Issue by luigireggi** [level73/Monithon#34]
forse mancano dati da APIs che danno problemi?

**Comment by luigireggi** [comment]
same for https://dev.monithon.it/report/view/174

**Comment by luigireggi** [comment]
same for https://dev.monithon.it/report/view/179

**Comment by IronRunes** [comment]
sistemato per quando manca la data di fine progetto. per quanto riguarda i report senza API bisogna inventare qualcosa di diverso, ma ho delle idee

**Comment by luigireggi** [comment]
ok. oltre alla data forse manca anche altro https://dev.monithon.it/report/view/174

**Comment by IronRunes** [comment]
in questo caso specifico non hanno generato il monitutor e quindi non hanno salvato i dati dell'API nel nostro DB. ho sistemato manualmente, chiudo questa e preparo un nuovo issue per questa istanza specifica, ed una per i report che sono correttamente senza API (i.e. monitoraggi europei)
