### ISSUE TITLE
Forzare save dei dati JSON delle API

### ISSUE THREAD

**Issue by IronRunes** [level73/Monithon#37]
Nel caso in cui non venga triggerato il monitutor i dati delle API non vengono recepiti dalla piattaforma. Eseguire controllo sulla validazione di questi dati ed in caso forzare una richiesta direttamente nel controller.

**Comment by luigireggi** [comment]
NOn so se è chiusa

**Comment by IronRunes** [comment]
é pending deployment, possiamo chiudere che va su con il prossimo push :D
