### ISSUE TITLE
Preparare possibile visualizzazione in caso di mancati dati delle API

### ISSUE THREAD

**Issue by IronRunes** [level73/Monithon#38]
Nei casi in cui non abbiamo dati che provengono dalle API, preparare una visualizzazione alternativa del report.

**Comment by luigireggi** [comment]
errori in report 210, 215

**Comment by luigireggi** [comment]
217

**Comment by IronRunes** [comment]
sistemati gli errori. 
in 2 casi hanno salvato senza far apparire il Monitutor (mancavano i dati delle API nel db)

**Comment by luigireggi** [comment]
il report 250 fa riferimento a un progetto che prima c'era su OC e ora non c'è più.
Quindi ADIOS APIs :)

**Comment by IronRunes** [comment]
> il report 250 fa riferimento a un progetto che prima c'era su OC e ora non c'è più.
> Quindi ADIOS APIs :)

nel caso specifico, la url al portale OC è stato aggiunto nelle fonti invece che nel campo della URL. 
ripristinato!

**Comment by luigireggi** [comment]
in realtà il progetto che hanno scelto è questo , che si chiamava MUSEO CARLO RAMBALDI: https://opencoesione.gov.it/it/progetti/23empg2017117201/
Ora però è uscito dal db di OC e non credo che sia accessibile via APIs: puoi verificare?
io ho già scritto mail a OC chiedendo di mantenere i dati dei progetti usciti in una sorta di archivio.

Un'altra possibilità è che ti passo io i dati che ho salvato dal CSV di ottobre, prima che il progetto fosse eliminato dal db di OC.

**Comment by luigireggi** [comment]
ti mando i dati sul progetto via mail

**Comment by luigireggi** [comment]
Recap:
- 4 report ASOC EU, di cui 2 pronti in attesa di pubblicazione appena pronta la viz senza APIs
- report ID 250 con dati su progetto da sostituire con quelli mandati via email su MUSEO CARLO RAMBALDI

**Comment by luigireggi** [comment]
salgono a 4 i report ASOC EU pronti per la pubblicazione
