### ISSUE TITLE
Cambio nome utente

### ISSUE THREAD

**Issue by luigireggi** [level73/Monithon#39]
Non è detto che sia un problema diffuso, per ora due richieste di modifica (di cui una risolta creando nuovo utente con altra mail).

Se possibile bisognerebbe cambiare nome utente di questo team da "illuminati" in "acca20": https://dev.monithon.it/user/update/106
Loro hanno già report approvato.

**Comment by luigireggi** [comment]
Occorre anche forzare modifica dell'ID ASOC per lo stesso utente 106: 19-20_0044

**Comment by IronRunes** [comment]
fixed
