### ISSUE TITLE
Development - Modifiche al form in italiano 

### ISSUE THREAD

**Issue by luigireggi** [level73/Monithon#4]
Fare modifiche al form in italiano contenute nel foglio “Form invio report EN” del file in https://docs.google.com/spreadsheets/d/1QyqBrZfnvhhwKqcVyQRPPfJs15DuXDGNbOLqbfvcecA/edit#gid=168892219  (in rosso)

**Comment by IronRunes** [comment]
@luigireggi ho lasciato un commento nello spreadsheet, ci sono 3 cambiamenti che vorrei essere sicuro di accoppiare correttamente :) 
Il resto è fatto, a breve push/pull!

**Comment by luigireggi** [comment]
risposto .)
