### ISSUE TITLE
Email vanno in spam su gmail

### ISSUE THREAD

**Issue by luigireggi** [level73/Monithon#45]

**Comment by luigireggi** [comment]
non hai ancora messo online le modifiche di ieri giusto? :)
manda ancora da redazione@monithon

**Comment by IronRunes** [comment]
si, sto finalizzando l'integrazione della libreria nell'app. ieri abbiamo scritto i test che hanno funzionato, oggi ho sistemato il codice dell'app per usare la libreria (i test in locale stanno funzionando), stasera/domani mando online e chiudo l'issue. :)

**Comment by luigireggi** [comment]
ah ecco, ops :)
