### ISSUE TITLE
report 152: campo non si modifica

### ISSUE THREAD

**Issue by luigireggi** [level73/Monithon#50]
risposta "Intervista con gli utenti/beneficiari dell'intervento" in step 2. Spunta messa per sbaglio ora non si riesce a rimuovere

**Comment by luigireggi** [comment]
in report 58 togliere "referenti politici"

**Comment by IronRunes** [comment]
trovato il bug, sto procedendo a sistemarlo

**Comment by IronRunes** [comment]
ok, sistemato il bug e sembra funzionare tutto (rimosso il flag da report 58)
