### ISSUE TITLE
le date dei report sono weird :) da rivedere/capire

### ISSUE THREAD

**Issue by luigireggi** [level73/Monithon#56]

**Comment by IronRunes** [comment]
care to elaborate? :D

**Comment by luigireggi** [comment]
:D
le date di creazione (forse) e ultima modifica (probabilmente) non mi sembrano corrette. anche alcuni dei ragazzi hanno segnalato

**Comment by IronRunes** [comment]
ci sono dei casi specifici che posso guardare? perchè quelle le spara il database, difficile che si sbagli - ma ovviamente indago!

**Comment by IronRunes** [comment]
forse il problema è che noi scriviamo "inviato il dd/mm/yyyy" ma in realtà quella è la data di ultima modifica (quindi di pubblicazione)

**Comment by luigireggi** [comment]
es. di ora: il report 74 ha ultima modifica 2020-02-17 16:45:04
E' impossibile perché lo hanno salvato un minuto fa.

sono in https://dev.monithon.it/user/edit#my-reports

**Comment by IronRunes** [comment]
quindi parliamo dell'elenco in pagina profilo, ok
ora vedo (cmq il dato nel db è corretto, meno male)

**Comment by luigireggi** [comment]
sì secondo me lì c'è una data che non è ultima modifica, è un'altra :))

**Comment by IronRunes** [comment]
allora, c'è una differenza importante tra i tipi di utenti  a livello di query, devo fare un'indagine più approfondita - cmq probabilmente quelle date sono le date di ultima modifica del profilo utente

**Comment by luigireggi** [comment]
ok thanks!!
