### ISSUE TITLE
ricostruire il processo di revisione report

### ISSUE THREAD

**Issue by luigireggi** [level73/Monithon#61]
1) ti viene facile sapere per ogni report quante volte è stato inviato, poi rimesso in bozza dalla redazione, poi reinviato e approvato?
2) sappiamo quanti report approvati hanno avuto commenti alla redazione?
3) riesci a contare quanti report sono stati modificati dal mio account? (es. modifica dei campi)
Lo potremmo usare per fare delle statistiche e valorizzare il lavoro notevole di questi giorni.
Se è complicato fare una misurazione precisa, posso anche andare a occhio...

**Comment by IronRunes** [comment]
la seconda è facile, la prima e la terza non posso. 
se però interessa questo aspetto di auditing (purtroppo per il futuro), possiamo implementarlo!

**Comment by luigireggi** [comment]
cool!
Andiamo con la 2! :)

**Comment by IronRunes** [comment]
23 report hanno ricevuto commenti dalla redazione
posso pure esplodere e vedere quale campo è stato il più commentato

**Comment by luigireggi** [comment]
aggiunto i dati qui nel piccolo "CRM":
https://docs.google.com/spreadsheets/d/12IX23JoYIRbk-WrbQb17_APymdRLhKcZvzRQVHVdNoE/edit#gid=0

allora direi che abbiamo le query salvate e siamo apposstttt
