### ISSUE TITLE
Query su utenti

### ISSUE THREAD

**Issue by luigireggi** [level73/Monithon#62]
tabella utenti con info profilo: città, bio, avatar, ID ASOC, istituto, tipo istituto, link al blog + altro rilvante.

Serve per valutare info inserite e mandare reminder o correzioni da fare.
Quando abbiamo ID asoc per tutti possiamo importare su report>view il blog ASOC.

**Comment by IronRunes** [comment]
mando CSV intanto. 
Una cosa da considerare è quella di compilare queste richieste in una serie di User Stories, così le infiliamo in backlog e le facciamo diventare feature della piattaforma

**Comment by luigireggi** [comment]
sì magari. questa diventa rountinaria di sicuro

**Comment by IronRunes** [comment]
ok, preparo progetto qui su GH

**Comment by luigireggi** [comment]
Ok allora approfitto e affino la richiesta per prossima volta:

**ID utente** | username | **ha report_approvato[sì/no]** | email | ID_ASOC | istituto | tipo_istituto | comune | link_blog | link_elaborato | region | provincia | **bio** | tipologia **utente** | **account attivo**
