### ISSUE TITLE
Ricerca nelle news

### ISSUE THREAD

**Issue by luigireggi** [level73/Monithon#7]
A me cerca su google.news.com e non trova mai nulla. E' perché ho lingua settata in inglese?
Se cerco su sito italiano trova cose.

**Comment by IronRunes** [comment]
@luigireggi si, se cerchi in IT trovi qualcosina ogni tanto ma dipende tanto dal titolo del progetto, che è la nostra chiave per la query. 
credo ci sia un modo per forzare la cosa, creo una Issue apposita.

**Comment by IronRunes** [comment]
Merged with 
#9
