### ISSUE TITLE
change data invio report 

### ISSUE THREAD

**Issue by luigireggi** [level73/Monithon#70]
se possibile data in report view dovrebbe essere data in cui il report è stato inviato alla redazione.
Ora mostra data ultimo salvataggio (che potrebbe avvenire anche mesi dopo, visto che gli si sta dando tempo per completare video di monitoraggio civico)

**Comment by IronRunes** [comment]
si può pensare, ma serve ragionarci bene - esempio: 
- Team invia il report (salvo la data)
- Redazione lo rimanda indietro con correzioni da fare
- Team sistema il report, lo invia (di nuovo)

Abbiamo potenziali N invii di report, qual'è la data che fa fede in uno scenario come questo? :)

**Comment by luigireggi** [comment]
metterei la data del primo invio perchè è la più vicina al momeento in cui hanno raccolto i dati
