### ISSUE TITLE
report 253 data too long for 'api_data'

### ISSUE THREAD

**Issue by luigireggi** [level73/Monithon#74]

**Comment by IronRunes** [comment]
Modificato il tipo della colonna api_data e inserito il contenuto manualmente - ora è ok, non dovrebbe ricapitare

**Comment by luigireggi** [comment]
yeah. magari per il futuro possiamo visualizzare tipo max 10 soggetti. ora sono decine e per vedere il video bisogna farsi venire il callo al dito dello scroll :D

**Comment by IronRunes** [comment]
si ci sto lavorando proprio ora :D

**Comment by luigireggi** [comment]
tra l'altro: stessa cosa per la monitutor

**Comment by IronRunes** [comment]
ok sistemata la visualizzazione in report/view, poi vedo come fare in Monitutor
