### ISSUE TITLE
index reports

### ISSUE THREAD

**Issue by luigireggi** [level73/Monithon#76]
- [x] togliere per ora "Abbiamo 115 report su Monithon!". In realtà sono molti più contando quelli degli anni passati. Lo rimettiamo una volta importati

- [x] Autore del report è il nome dell'user

- [x] Titolo del report sempre in MAIUSCOLO, così è uniforme

- [x] Le immagini si caricano full-size. E' possibile creare un'anteprima? Se non è complicato...

- [x] Dove non ci sono immagini spesso c'è anche poco testo e il box risulta vuoto. Hai provato a mettere un'immagine placeholder per vedere come sta? Tipo una lente di ingrandimento... una cosa non troppo evidente.

- [x] Sposterei l'elenco dei report di mezzo cm. sulla sinistra così da allinearlo con il titolo della pagina

**Comment by IronRunes** [comment]
replies: 

1. Autore del report al momento è campo "autore" del form, se valorizzato - altrimenti è nome utente. devo portarlo a nome utente sempre?
2. le immagini si caricano in un quadrato, forse devi fare un hard-refresh? oppure mandami uno screenshot, così vedo cosa vedi ;)
3. ok per il placeholder
4. se allineo a sx, poi quando fai l'hover sul box del report il testo risulta molto appiccicato al bordo. secondo me devi pulire cache ;)

**Comment by luigireggi** [comment]
1. yes please!
 2. sisi le vedo in un quadrato!!
3.
 4. hai ragione non avevo contato il box hover!!!

**Comment by luigireggi** [comment]
ma poi forse l'hover nel rettangolino lo toglierei... lasciandolo fisso.

**Comment by luigireggi** [comment]
altra idea:
3. per l'immagine si potrebbe forse: prendere frame del video youtube se c'è (si può fare in automatico...?) oppure immagine della mappetta

**Comment by IronRunes** [comment]
allora, anche qui fatto tutto @luigireggi . per l'immagine, il modo più veloce di caricare la pagina è usare una delle risorse sui ns server - per il momento lascerei così
