### ISSUE TITLE
Step 3 "Con quali soggetti avete creato delle connessioni per discutere dei risultati del vostro monitoraggio?"

### ISSUE THREAD

**Issue by luigireggi** [level73/Monithon#78]
- [x] Inserire un "cosa devo fare qui" per la domanda "Con quali soggetti avete creato delle connessioni per discutere dei risultati del vostro monitoraggio?", come da google slide:

"
RUOLO. Elencate i soggetti con cui avete avuto dei contatti per diffondere o discutere i risultati del vostro monitoraggio.
Ad esempio: Sindaco, Presidente, Funzionario pubblico, giornalista, amministratore delegato di azienda, etc

ORGANIZZAZIONE. Ad esempio: Città di Roma, Provincia di Chieti, Regione Calabria, Il Corriere della Sera, Buitoni
"

- [x] Per opzione "altro - specificare" non c'è possibilità di inserire testo.  Per semplicità: togliamolo dall'elenco.

- [x] Dal secondo soggetto in poi "tipo di connessione" è in bold con sfondo, andrebbe reso omogeneo agli altri

- [x] aggiungendo un soggetto, il nome del primo soggetto viene copiato dentro al campo

- [x] quando salvo sparisce il contenuto del "tipo di connessione", primo soggetto.

**Comment by IronRunes** [comment]
fatto
