### ISSUE TITLE
"Home" e logo monithon in alto a sx devono puntare a home page del blog

### ISSUE THREAD

**Issue by luigireggi** [level73/Monithon#90]

**Comment by luigireggi** [comment]
qui dovremmo capire qual è la soluzione migliore... vedo che tutti cliccano sul logo monithon per tornare all'home page del SITO (BLOG) e sono frustrati di trovare una landing page vuota :-D
Anche "Home" forse si può togliere.
Di contro, il rischio è di saltare continuamente dal wordpress alla app....
Idee?

**Comment by IronRunes** [comment]
@luigireggi Messo che il logo punta a Wordpress. 
Home punta alla landing page. 
Sulla landing page a breve potremmo mettere i "link utili", tipo project finder, report finder, Open Coesione, riferimenti alle API... 
Apriremo altra Issue al momento giusto
