### ISSUE TITLE
Aggiungere testo a landing page main

### ISSUE THREAD

**Issue by luigireggi** [level73/Monithon#98]
https://it.monithon.eu/

Testo:

Benvenuto!

Questa è la piattaforma di lavoro di Monithon per la creazione e l’invio dei report di monitoraggio civico.
Vai su “Nuovo Report” per creare un report di monitoraggio. Per attivare la guida MoniTutor, incolla la URL della pagina del progetto che hai scelto su OpenCoesione nel primo campo.
Per leggere i report già pubblicati, vai su “Report".

**Comment by IronRunes** [comment]
fatto.
